### ISSUE TITLE
Add `--depth 1` in `install_theme.sh`

### ISSUE THREAD

**Issue by meta-network-team** [Meta-Network/meta-hexo-starter-custom#12]
``` bash
git clone --depth 1 <theme_repo_url> themes/<theme_name>
```

Reduce the time to install the theme

- [x] cactus
- [x] Freemind.386
- [x] lite
- [x] yilia-plus
- [x] disapora
- [x] obsidian
- [x] apollo
- [x] Wikitten

**Comment by fzxiao233** [comment]
#16 
disapora

**Comment by AlotOfBlahaj** [comment]
all done
