### ISSUE TITLE
[BUG]Failed to start hexo server in the process of adding theme Wikitten 

### ISSUE THREAD

**Issue by Cloudifold** [Meta-Network/meta-hexo-starter-custom#9]
**Describe the bug**
A html page can't be shown at `localhost:4000`

**To Reproduce**
Follow the step of "Submitting a new theme template" in
https://github.com/Meta-Network/meta-hexo-starter-custom/blob/main/CONTRIBUTING.md
1. Create a theme branch.

    ``` bash
    $ git checkout -b theme/<theme_name>
    ```
   
2. Edit `install_theme.sh`:

    ```shell
    #!/bin/bash
    git clone https://github.com/zthxxx/hexo-theme-Wikitten.git themes/Wikitten
    ```

3. Install dependencies:
   
    ```bash
    # optional, check the theme's official documentation
    $ yarn add hexo hexo-autonofollow hexo-directory-category hexo-generator-archive hexo-generator-category hexo-generator-feed hexo-generator-index hexo-generator-json-content hexo-generator-sitemap hexo-generator-tag hexo-renderer-ejs hexo-renderer-marked hexo-renderer-stylus
    # see the section 'Add meta-space-config-filter'
    $ yarn add hexo-filter-meta-space 
    ```

4. Create `_config.Wikitten.yml` and delete the existed one. Edit `_config.yml` :
    ```yaml
    theme: Wikitten
    ```
5. Test :
    ``` bash
    $ ./install.sh
    $ yarn server --debug
    ```

**Expected behavior**
A html page can be shown at `localhost:4000`

**Screenshots**
![XXX](https://user-images.githubusercontent.com/55614332/139589837-e9e05c75-1391-437e-b0f2-41c9ac582326.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux 5.14.14-arch1-1 
 - Browser Firefox
 - Version 93.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by casimir-crystal** [comment]
The problem is due to the lack of configuration file content for the theme. Refer to the official document:

> 3. Rename the `_config.yml.example` to `_config.yml` so you can config theme
> 
> ```bash
> $ cp -f themes/Wikitten/_config.yml.example themes/Wikitten/_config.yml
> # edit and customize it
> $ vim themes/Wikitten/_config.yml
> ```

To this problem, you can run this command:

```bash
$ cp -f themes/Wikitten/_config.yml.example _config.Wikitten.yml
```

But, we should have mentioned this in the documentation, so I'll update the `CONTRIBUTING.md` later.
